version: '3.9'
services:

  db:
    image: mysql:8.0.32
    restart: always
    environment:
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: eth
      MYSQL_DATABASE: eth
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    restart: always
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
